pyfechas/urls.py
# -*- coding: utf-8 -*-

"""pyfechas URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from registro_fechas import views

urlpatterns = [
    url(r'^registro_fechas/search', views.home, name='home'),
    url(r'^registro_fechas/new', views.new, name='new'),
    url(r'^admin/', include(admin.site.urls)),
]

registro_fechas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^search$', views.new, name='home'),
    url(r'^new$', views.new, name='new'),
]

registro_fechas/models.py
from django.db import models

# Create your models here.


class RegistroFechas(models.Model):
    nombre = models.TextField()

registro_fechas/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect

# Create your views here.

from django.http import HttpRequest
from registro_fechas.models import RegistroFechas


def new(request):
    if request.method == 'GET':
        return render(request, 'new.html')
    elif request.method == 'POST':
        registro = RegistroFechas()
        registro.nombre = request.POST.get('nombre', '')
        registro.save()
        return redirect('home')


def home(request):
    return render(request, 'home.html')

registro_fechas/templates/home.html
<html>
    <head>
        <title>Registro de Fechas - Página de inicio</title>
    </head>
    <body>
        <h1> Bienvenido a la aplicación del registro de fechas</h1>
    </body>
</html>

registro_fechas/templates/new.html
<html>
    <head>
        <title>Registro de Fechas - Nuevo</title>
    </head>
    <body>
        <h1>Registro de Fechas - Nuevo</h1>
        <form method="POST">
            <div>
                <label for="id_nombre"> Nombre </label>
                <input id="id_nombre">
                {% csrf_token %}
            </div>
            <button type="submit">Guardar cambios</button>
        </form>

    </body>
</html>